name: Flutter CI

on:
  push:
    branches:
      - dev
      - feature/**

  pull_request:
    branches:
      - dev
      - main

jobs:

  # job 1: analyze (jalan di semua branch)
  analyze:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.9"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

  # job 2: build (hanya dev & PR main)
  build:
    runs-on: ubuntu-latest
    needs: analyze # hanya jalan jika analyze tidak ada error

    if: github.ref == 'refs/heads/dev' || github.base_ref == 'main'

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.9"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: mobile/build/app/outputs/flutter-apk/app-debug.apk